#!/usr/bin/env python3
"""Batch article assembly with a hard pre-flight spend gate.

Generating a single page is one cheap API call; a corpus backfill is real money.
This driver estimates the spend BEFORE touching the metered API, prints the
figure, and refuses to generate anything without an explicit --confirm. There is
no way to spend through this tool without seeing the estimate first.

  # estimate only (no spend) - the default
  python batch.py --nodes-file tier1.txt
  python batch.py --records-file records.txt --model haiku
  python batch.py --nodes "Fravor, David" "Mellon, Christopher K."

  # generate, after the estimate has been seen and the amount cleared
  python batch.py --nodes-file tier1.txt --confirm

Each item is generated by shelling out to assembler.py (one --node / --record
run), so it uses the exact single-page path and the same ANTHROPIC_API_KEY.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

import assembler as asm

# USD per 1,000,000 tokens, (input, output). Source: claude-api model table.
PRICING = {
    "sonnet": (3.00, 15.00),
    "opus": (5.00, 25.00),
    "haiku": (1.00, 5.00),
}
# Deliberately conservative: ~3.5 chars/token over-counts slightly vs the real
# tokenizer, and a generous fixed output ceiling per article. The estimate
# should never come in UNDER the actual spend.
CHARS_PER_TOKEN = 3.5
EST_OUTPUT_TOKENS = 3000


def _read_items(args, kind: str) -> list[str]:
    """Gather the work list for `kind` ('nodes' | 'records') from the positional
    list or the corresponding --<kind>-file (one item per line, # comments ok)."""
    items: list[str] = list(getattr(args, kind) or [])
    fpath = getattr(args, f"{kind[:-1]}s_file", None) or getattr(
        args, f"{kind}_file", None
    )
    if fpath:
        for line in Path(fpath).read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                items.append(line)
    return items


def _prompt_chars(args, kind: str, item: str) -> int | None:
    """Build the assembly prompt for one item read-only (no API) and return its
    character count, or None if the item can't be resolved."""
    if kind == "nodes":
        import sqlite3

        conn = sqlite3.connect(args.db)
        node = asm.load_node(conn, item)
        if not node:
            return None
        claims = asm.claims_for_node(conn, node["id"])
        related = asm.related_nodes(conn, node["id"])
    elif kind == "briefs":
        loaded = asm.load_brief(Path(args.briefs_root), item)
        if not loaded:
            return None
        brief, _slug = loaded
        node = asm.brief_node(brief)
        claims = asm.claims_from_brief(brief)
        related = asm.related_from_brief(brief)
    else:
        loaded = asm.load_digest(Path(args.digests_root), item)
        if not loaded:
            return None
        digest, friendly_name = loaded
        node = asm.record_node(digest, friendly_name)
        claims = asm.claims_from_digest(digest)
        related = asm.related_from_digest(digest)
    return len(asm.build_prompt(node, claims, related))


def estimate(args, kind: str, items: list[str]) -> tuple[list[str], list[str]]:
    """Print the spend estimate. Returns (resolved, unresolved) item lists."""
    in_price, out_price = PRICING.get(args.model, PRICING["sonnet"])
    resolved: list[str] = []
    unresolved: list[str] = []
    total_in_tokens = 0
    for item in items:
        chars = _prompt_chars(args, kind, item)
        if chars is None:
            unresolved.append(item)
            continue
        resolved.append(item)
        total_in_tokens += round(chars / CHARS_PER_TOKEN)

    out_tokens = len(resolved) * EST_OUTPUT_TOKENS
    in_cost = total_in_tokens * in_price / 1_000_000
    out_cost = out_tokens * out_price / 1_000_000
    total = in_cost + out_cost
    on_api = asm._use_api()

    print("=" * 60, file=sys.stderr)
    if on_api:
        print("BATCH SPEND ESTIMATE (metered Anthropic API)", file=sys.stderr)
    else:
        print(
            "BATCH PRE-FLIGHT (Claude subscription - NO metered spend)",
            file=sys.stderr,
        )
    print(
        f"  {len(resolved)} {kind} x model={args.model} "
        f"(${in_price:.2f}/${out_price:.2f} per 1M in/out)",
        file=sys.stderr,
    )
    print(
        f"  input ~{total_in_tokens:,} tokens, output ~{out_tokens:,} tokens "
        f"(~{EST_OUTPUT_TOKENS}/item)",
        file=sys.stderr,
    )
    if on_api:
        print(
            f"  ESTIMATED METERED COST: ${total:,.2f}  (conservative; actual usually lower)",
            file=sys.stderr,
        )
    else:
        print(
            f"  Runs on Mark's Max subscription - no dollar spend, draws on plan "
            f"rate limits. (Would cost ~${total:,.2f} on the metered API; set "
            f"ASSEMBLER_USE_API=1 to use it.)",
            file=sys.stderr,
        )
    if unresolved:
        print(
            f"  {len(unresolved)} unresolved (skipped): {', '.join(unresolved[:5])}"
            + (" ..." if len(unresolved) > 5 else ""),
            file=sys.stderr,
        )
    print("=" * 60, file=sys.stderr)
    return resolved, unresolved


def generate(args, kind: str, items: list[str]) -> int:
    flag = {"nodes": "--node", "records": "--record", "briefs": "--brief"}[kind]
    common = [
        "--model",
        args.model,
        "--content-root",
        args.content_root,
    ]
    if kind == "nodes":
        common += ["--db", args.db]
    elif kind == "briefs":
        # Briefs are the sole source, but the digests-root lets the assembler
        # carry forward each contributing record's ai_usage into the article.
        common += [
            "--briefs-root",
            args.briefs_root,
            "--digests-root",
            args.digests_root,
        ]
    else:
        common += ["--digests-root", args.digests_root]
    ok = 0
    failed: list[str] = []
    for i, item in enumerate(items, 1):
        if i > 1 and args.delay:
            # Space calls out so a paced run doesn't burst the shared
            # subscription rate-limit (each call is already sequential).
            time.sleep(args.delay)
        print(f"\n=== [{i}/{len(items)}] {item} ===", file=sys.stderr)
        proc = subprocess.run(
            [sys.executable, "assembler.py", flag, item, *common],
            cwd=str(Path(__file__).parent),
        )
        if proc.returncode == 0:
            ok += 1
        else:
            failed.append(item)
    print(f"\nBatch: {ok} ok, {len(failed)} failed", file=sys.stderr)
    if failed:
        print("failed:", file=sys.stderr)
        for f in failed:
            print(f"  {f}", file=sys.stderr)
    return 0 if not failed else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--nodes", nargs="*", help="Node names/uuids to assemble")
    ap.add_argument("--records", nargs="*", help="Record digest names to assemble")
    ap.add_argument("--briefs", nargs="*", help="Brief page-slugs to assemble")
    ap.add_argument(
        "--nodes-file", help="File of node names, one per line (# comments ok)"
    )
    ap.add_argument("--records-file", help="File of record digest names, one per line")
    ap.add_argument("--briefs-file", help="File of brief page-slugs, one per line")
    ap.add_argument(
        "--db", default=asm.DEFAULT_DB, help="knowledge.db path (node mode)"
    )
    ap.add_argument(
        "--digests-root",
        default=asm.DEFAULT_DIGESTS_ROOT,
        help="digests repo (record mode; brief mode ai_usage carry-forward)",
    )
    ap.add_argument(
        "--briefs-root",
        default=asm.DEFAULT_BRIEFS_ROOT,
        help="briefs dir (brief mode)",
    )
    ap.add_argument("--content-root", default=asm.DEFAULT_CONTENT_ROOT)
    ap.add_argument("--model", default=asm.DEFAULT_MODEL, help="sonnet | opus | haiku")
    ap.add_argument(
        "--delay",
        type=float,
        default=0.0,
        help="Seconds to wait between calls, to pace a run against the shared "
        "subscription rate-limit (calls are sequential regardless).",
    )
    ap.add_argument(
        "--confirm",
        action="store_true",
        help="Spend money: generate the batch. Without this, only the estimate prints.",
    )
    args = ap.parse_args()

    nodes = _read_items(args, "nodes")
    records = _read_items(args, "records")
    briefs = _read_items(args, "briefs")
    chosen = [
        (k, v)
        for k, v in (("nodes", nodes), ("records", records), ("briefs", briefs))
        if v
    ]
    if len(chosen) != 1:
        print(
            "provide exactly one of --nodes / --records / --briefs (or their -file form)",
            file=sys.stderr,
        )
        return 2
    kind, items = chosen[0]

    resolved, _ = estimate(args, kind, items)
    if not args.confirm:
        tail = (
            "once the dollar amount above is cleared"
            if asm._use_api()
            else "to generate on the subscription"
        )
        print(
            f"\nPre-flight only - nothing generated. Re-run with --confirm {tail}.",
            file=sys.stderr,
        )
        return 0
    if not resolved:
        print("nothing resolved to generate", file=sys.stderr)
        return 2
    return generate(args, kind, resolved)


if __name__ == "__main__":
    sys.exit(main())
