#!/usr/bin/env python3
"""Batch article assembly with a hard pre-flight spend gate.

Generating a single page is one cheap API call; a corpus backfill is real money.
This driver estimates the spend BEFORE touching the metered API, prints the
figure, and refuses to generate anything without an explicit --confirm. There is
no way to spend through this tool without seeing the estimate first.

  # estimate only (no spend) - the default
  python batch.py --nodes-file tier1.txt
  python batch.py --records-file records.txt --model haiku
  python batch.py --nodes "Fravor, David" "Mellon, Christopher K."

  # generate, after the estimate has been seen and the amount cleared
  python batch.py --nodes-file tier1.txt --confirm

Each item is generated by shelling out to assembler.py (one --node / --record
run), so it uses the exact single-page path and the same ANTHROPIC_API_KEY.

Built to be left alone for days. Two things follow from that:

- A full plan window is NOT a failure. The assembler exits 75 on plan throttling
  with the reset time, and this driver sleeps out the window and retries the same
  item. Counting throttling as a failure is how a batch reports a hundred good
  briefs as broken because the plan was busy for an hour.
- Real breakage stops the run. A separate consecutive-hard-failure counter aborts
  after --max-consecutive-failures, so a systemic fault (a missing briefs root, a
  broken model id) costs a handful of items rather than the whole list.

The run ends with a Hugo build, so a page that breaks the site surfaces now
rather than whenever someone next builds.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

import assembler as asm

# USD per 1,000,000 tokens, (input, output). Source: claude-api model table.
PRICING = {
    "sonnet": (3.00, 15.00),
    "opus": (5.00, 25.00),
    "haiku": (1.00, 5.00),
}
# Measured, not assumed. The previous constants (3.5 chars/token, 3000 output
# tokens, no per-call overhead) under-estimated a real run by ~3x on input and
# ~9x on output, which breaks the one promise this file makes - that the figure
# printed before a metered run is never lower than the spend that follows.
#
# Fitted against three assembles on claude-sonnet-5 (2026-07-31): prompts of
# 120,941 / 132,009 / 60,500 chars reported 80,946 / 84,221 / 57,682 input
# tokens. Two unknowns, three points: solving the extremes gives a fixed
# per-call overhead plus a density, and the held-out middle point predicts to
# +1.2%. The fixed term is the CLI's own system prompt, which is charged on
# every call however small the brief - the reason a per-char-only estimate is
# hopeless for short items.
# Single-sourced in assembler.py so the batch pre-flight and the single-run gate
# cannot quote different numbers for the same work. (Observed output: 7,829 /
# 25,728 / 31,023 - the model re-emits every reference block into the front
# matter, so output tracks reference count, not prose length. Ceiling by design.)
CHARS_PER_TOKEN = asm.CHARS_PER_TOKEN
FIXED_INPUT_TOKENS = asm.FIXED_INPUT_TOKENS
EST_OUTPUT_TOKENS = asm.EST_OUTPUT_TOKENS


def _read_items(args, kind: str) -> list[str]:
    """Gather the work list for `kind` ('nodes' | 'records') from the positional
    list or the corresponding --<kind>-file (one item per line, # comments ok)."""
    items: list[str] = list(getattr(args, kind) or [])
    fpath = getattr(args, f"{kind[:-1]}s_file", None) or getattr(
        args, f"{kind}_file", None
    )
    if fpath:
        for line in Path(fpath).read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                items.append(line)
    return items


def _target_path(args, kind: str, item: str) -> Path | None:
    """Where this item would be written, resolved without generating anything."""
    node = _resolve_node(args, kind, item)
    if node is None:
        return None
    section = asm.SECTION_BY_TYPE.get(node["type"], node["type"] + "s")
    return asm.output_path(Path(args.content_root), section, asm.node_slug(node))


def _check_slug_collisions(args, kind: str, items: list[str]) -> dict[str, list[str]]:
    """Items in this run that would write to the SAME file.

    Two live nodes can compete for one URL - the graph currently has five such
    pairs, including one at 144 claims against 5. Assembling both writes the same
    path twice and the second silently wins, so the page is decided by list order
    and the loss is invisible. Caught here rather than at write time because a
    pre-flight costs nothing and a discovered overwrite costs a whole article.
    """
    seen: dict[str, list[str]] = {}
    for item in items:
        path = _target_path(args, kind, item)
        if path is not None:
            seen.setdefault(str(path), []).append(item)
    return {p: its for p, its in seen.items() if len(its) > 1}


def _load(args, kind: str, item: str):
    """(node, claims, related) for one item, read-only, or None if unresolvable.
    The single place a work item is turned into the assembler's inputs, so the
    pre-flight and the estimate cannot disagree about what an item resolves to."""
    if kind == "nodes":
        import sqlite3

        conn = sqlite3.connect(args.db)
        node = asm.load_node(conn, item)
        if not node:
            return None
        return (
            node,
            asm.claims_for_node(conn, node["id"]),
            asm.related_nodes(conn, node["id"]),
        )
    if kind == "briefs":
        loaded = asm.load_brief(Path(args.briefs_root), item)
        if not loaded:
            return None
        brief, _slug = loaded
        return (
            asm.brief_node(brief),
            asm.claims_from_brief(brief),
            asm.related_from_brief(brief),
        )
    loaded = asm.load_digest(Path(args.digests_root), item)
    if not loaded:
        return None
    digest, friendly_name = loaded
    return (
        asm.record_node(digest, friendly_name),
        asm.claims_from_digest(digest),
        asm.related_from_digest(digest),
    )


def _resolve_node(args, kind: str, item: str) -> dict | None:
    loaded = _load(args, kind, item)
    return loaded[0] if loaded else None


def _prompt_chars(args, kind: str, item: str) -> int | None:
    """Build the assembly prompt for one item read-only (no API) and return its
    character count, or None if the item can't be resolved."""
    loaded = _load(args, kind, item)
    if loaded is None:
        return None
    node, claims, related = loaded
    return len(asm.build_prompt(node, claims, related))


def estimate(args, kind: str, items: list[str]) -> tuple[list[str], list[str]]:
    """Print the spend estimate. Returns (resolved, unresolved) item lists."""
    in_price, out_price = PRICING.get(args.model, PRICING["sonnet"])
    resolved: list[str] = []
    unresolved: list[str] = []
    total_in_tokens = 0
    for item in items:
        chars = _prompt_chars(args, kind, item)
        if chars is None:
            unresolved.append(item)
            continue
        resolved.append(item)
        total_in_tokens += FIXED_INPUT_TOKENS + round(chars / CHARS_PER_TOKEN)

    out_tokens = len(resolved) * EST_OUTPUT_TOKENS
    in_cost = total_in_tokens * in_price / 1_000_000
    out_cost = out_tokens * out_price / 1_000_000
    total = in_cost + out_cost
    on_api = asm._use_api()

    print("=" * 60, file=sys.stderr)
    if on_api:
        print("BATCH SPEND ESTIMATE (metered Anthropic API)", file=sys.stderr)
    else:
        print(
            "BATCH PRE-FLIGHT (Claude subscription - NO metered spend)",
            file=sys.stderr,
        )
    print(
        f"  {len(resolved)} {kind} x model={args.model} "
        f"(${in_price:.2f}/${out_price:.2f} per 1M in/out)",
        file=sys.stderr,
    )
    print(
        f"  input ~{total_in_tokens:,} tokens, output ~{out_tokens:,} tokens "
        f"(~{EST_OUTPUT_TOKENS}/item)",
        file=sys.stderr,
    )
    if on_api:
        print(
            f"  ESTIMATED METERED COST: ${total:,.2f}  (conservative; actual usually lower)",
            file=sys.stderr,
        )
    else:
        print(
            f"  Runs on Mark's Max subscription - no dollar spend, draws on plan "
            f"rate limits. (Would cost ~${total:,.2f} on the metered API; set "
            f"ASSEMBLER_USE_API=1 to use it.)",
            file=sys.stderr,
        )
    if unresolved:
        print(
            f"  {len(unresolved)} unresolved (skipped): {', '.join(unresolved[:5])}"
            + (" ..." if len(unresolved) > 5 else ""),
            file=sys.stderr,
        )
    print("=" * 60, file=sys.stderr)
    return resolved, unresolved


def _run_one(cmd: list[str]) -> tuple[int, float | None]:
    """Run one assembler call. Returns (exit code, plan reset epoch or None).

    stderr is streamed rather than captured whole: an article can take minutes
    and a batch left running for days needs to show progress as it happens, not
    in a burst when each item exits. The plan-limit marker is picked out of that
    same stream on the way past.
    """
    reset: float | None = None
    proc = subprocess.Popen(
        cmd,
        cwd=str(Path(__file__).parent),
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    for line in proc.stderr:
        sys.stderr.write(line)
        if line.startswith(asm._PLAN_LIMIT_MARKER):
            _, _, raw = line.partition("reset_at=")
            raw = raw.strip()
            if raw and raw != "-":
                try:
                    reset = float(raw)
                except ValueError:
                    reset = None
    proc.stderr.close()
    return proc.wait(), reset


def _wait_out_window(reset: float | None, blind_waits: int) -> float:
    """Seconds to sleep before retrying a throttled item.

    With a reported reset, sleep to it plus a small buffer - the plan reports the
    real number, so guessing an interval only wastes the window. Without one,
    back off 15/30/60 minutes and hold at 60: a throttled call is rejected before
    it generates anything, so re-probing is cheap, but probing every minute for
    a weekly cap is pointless noise.
    """
    if reset is not None:
        return max(60.0, reset - time.time() + 60.0)
    return [900.0, 1800.0, 3600.0][min(blind_waits, 2)]


def _hugo_smoke_test(site_root: str) -> bool:
    """Build the site once, so a page that breaks Hugo surfaces at the end of the
    batch instead of whenever someone next builds. Read-only: the build writes to
    site/public, never to content."""
    site = Path(site_root).expanduser()
    if not (site / "hugo.toml").is_file():
        print(f"\nHugo smoke test SKIPPED: no hugo.toml under {site}", file=sys.stderr)
        return True
    print(f"\n=== Hugo smoke test ({site}) ===", file=sys.stderr)
    proc = subprocess.run(["npm", "run", "build"], cwd=str(site))
    if proc.returncode == 0:
        print("Hugo smoke test PASSED", file=sys.stderr)
        return True
    print(
        f"Hugo smoke test FAILED (exit {proc.returncode}) - a page written by this "
        "batch breaks the site build. The articles are on disk; fix before merging.",
        file=sys.stderr,
    )
    return False


def generate(args, kind: str, items: list[str]) -> int:
    flag = {"nodes": "--node", "records": "--record", "briefs": "--brief"}[kind]
    common = [
        "--model",
        args.model,
        "--content-root",
        args.content_root,
    ]
    # Carry this batch's --confirm through to each child's own spend gate. The
    # children are separate processes, so the authorisation this driver took
    # from the operator does not otherwise reach them, and the metered backstop
    # in _call_api would refuse every item. No-op on the subscription path,
    # which is not metered and never consults it.
    if asm._use_api() and getattr(args, "confirm", False):
        common.append("--confirm-spend")
    # The briefs root goes to every mode, not just --brief: it is also the
    # proposal set the body-link resolver indexes, and a record page links to
    # entities as heavily as an entity page does. Without it those links fall
    # back to whatever happens to be on disk at the time.
    common += ["--briefs-root", args.briefs_root, "--link-min-claims"]
    common += [str(args.link_min_claims)]
    if kind == "nodes":
        common += ["--db", args.db]
    elif kind == "briefs":
        # Briefs are the sole source, but the digests-root lets the assembler
        # carry forward each contributing record's ai_usage into the article.
        common += ["--digests-root", args.digests_root]
    else:
        common += ["--digests-root", args.digests_root]
    ok = 0
    failed: list[str] = []
    # Throttling and breakage are counted apart, and only the second one can end
    # the run. A shared counter is what turns a full plan window into a batch
    # that reports every remaining brief as failed - the failure this guards.
    consecutive_hard = 0
    throttled_waits = 0
    blind_waits = 0
    waited_total = 0.0
    max_wait = args.max_wait_hours * 3600.0
    i = 0
    while i < len(items):
        item = items[i]
        if i > 0 and args.delay:
            # Space calls out so a paced run doesn't burst the shared
            # subscription rate-limit (each call is already sequential).
            time.sleep(args.delay)
        print(f"\n=== [{i + 1}/{len(items)}] {item} ===", file=sys.stderr)
        code, reset = _run_one([sys.executable, "assembler.py", flag, item, *common])

        if code == asm._EXIT_PLAN_RATE_LIMITED:
            nap = _wait_out_window(reset, blind_waits)
            blind_waits = blind_waits + 1 if reset is None else 0
            if waited_total + nap > max_wait:
                print(
                    f"\nPlan throttled and the {args.max_wait_hours}h wait budget is "
                    f"spent. Stopping with {ok} done, {len(items) - i} not attempted.",
                    file=sys.stderr,
                )
                break
            waited_total += nap
            throttled_waits += 1
            until = time.strftime("%H:%M %Z", time.localtime(time.time() + nap))
            print(
                f"  plan window full - sleeping {nap / 60:.0f} min (until ~{until}), "
                f"then retrying this item. Not counted as a failure.",
                file=sys.stderr,
            )
            time.sleep(nap)
            continue  # same item, no strike, no advance

        if code == 0:
            ok += 1
            consecutive_hard = 0
        else:
            failed.append(item)
            consecutive_hard += 1
            if consecutive_hard >= args.max_consecutive_failures:
                print(
                    f"\nABORTING: {consecutive_hard} consecutive failures "
                    f"(--max-consecutive-failures). Something is broken beyond one "
                    f"bad brief; {len(items) - i - 1} items not attempted.",
                    file=sys.stderr,
                )
                i += 1
                break
        i += 1

    print(f"\nBatch: {ok} ok, {len(failed)} failed", file=sys.stderr)
    if throttled_waits:
        print(
            f"  paused {throttled_waits}x for the plan window "
            f"({waited_total / 3600:.1f}h total)",
            file=sys.stderr,
        )
    if failed:
        print("failed:", file=sys.stderr)
        for f in failed:
            print(f"  {f}", file=sys.stderr)
    site_root = args.site_root or str(
        Path(args.content_root).expanduser().resolve().parent / "site"
    )
    built = _hugo_smoke_test(site_root) if ok and not args.no_smoke_test else True
    return 0 if not failed and built else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--nodes", nargs="*", help="Node names/uuids to assemble")
    ap.add_argument("--records", nargs="*", help="Record digest names to assemble")
    ap.add_argument("--briefs", nargs="*", help="Brief page-slugs to assemble")
    ap.add_argument(
        "--nodes-file", help="File of node names, one per line (# comments ok)"
    )
    ap.add_argument("--records-file", help="File of record digest names, one per line")
    ap.add_argument("--briefs-file", help="File of brief page-slugs, one per line")
    ap.add_argument(
        "--db", default=asm.DEFAULT_DB, help="knowledge.db path (node mode)"
    )
    ap.add_argument(
        "--digests-root",
        default=asm.DEFAULT_DIGESTS_ROOT,
        help="digests repo (record mode; brief mode ai_usage carry-forward)",
    )
    ap.add_argument(
        "--briefs-root",
        default=asm.DEFAULT_BRIEFS_ROOT,
        help="briefs dir (brief mode)",
    )
    ap.add_argument("--content-root", default=asm.DEFAULT_CONTENT_ROOT)
    ap.add_argument("--model", default=asm.DEFAULT_MODEL, help="sonnet | opus | haiku")
    ap.add_argument(
        "--delay",
        type=float,
        default=0.0,
        help="Seconds to wait between calls, to pace a run against the shared "
        "subscription rate-limit (calls are sequential regardless).",
    )
    ap.add_argument(
        "--allow-slug-collisions",
        action="store_true",
        help="Proceed even when two items in the run write to the same file "
        "(last write wins). Off by default: the loss is otherwise invisible.",
    )
    ap.add_argument(
        "--link-min-claims",
        type=int,
        default=0,
        help="Claim floor below which a proposed page is not linkable. Set it to "
        "the floor this batch is assembling at, so articles do not link to pages "
        "the run will not write.",
    )
    ap.add_argument(
        "--max-consecutive-failures",
        type=int,
        default=5,
        help="Abort after this many consecutive HARD failures (default: 5). Plan "
        "throttling is not a failure and never counts towards this.",
    )
    ap.add_argument(
        "--max-wait-hours",
        type=float,
        default=24.0,
        help="Total time the batch may spend asleep waiting out plan windows "
        "before stopping with what it has (default: 24).",
    )
    ap.add_argument(
        "--site-root",
        help="Hugo site checked by the end-of-run smoke test (default: the "
        "'site' sibling of --content-root, which is how the repos are laid out)",
    )
    ap.add_argument(
        "--no-smoke-test",
        action="store_true",
        help="Skip the end-of-run Hugo build",
    )
    ap.add_argument(
        "--confirm",
        action="store_true",
        help="Spend money: generate the batch. Without this, only the estimate prints.",
    )
    args = ap.parse_args()

    nodes = _read_items(args, "nodes")
    records = _read_items(args, "records")
    briefs = _read_items(args, "briefs")
    chosen = [
        (k, v)
        for k, v in (("nodes", nodes), ("records", records), ("briefs", briefs))
        if v
    ]
    if len(chosen) != 1:
        print(
            "provide exactly one of --nodes / --records / --briefs (or their -file form)",
            file=sys.stderr,
        )
        return 2
    kind, items = chosen[0]

    resolved, _ = estimate(args, kind, items)

    clashes = _check_slug_collisions(args, kind, resolved)
    if clashes:
        print(
            f"\nSLUG COLLISION: {len(clashes)} output path(s) claimed by more than "
            "one item in this run. Assembling both writes the same file twice and "
            "the second silently wins, so list order would decide the page.",
            file=sys.stderr,
        )
        for path, its in clashes.items():
            print(f"  {path}\n      <- {', '.join(its)}", file=sys.stderr)
        if not args.allow_slug_collisions:
            print(
                "\nRefusing to run. Merge the duplicate nodes, or drop all but one "
                "of each set from the work list, or pass --allow-slug-collisions to "
                "accept last-write-wins.",
                file=sys.stderr,
            )
            return 2

    if not args.confirm:
        tail = (
            "once the dollar amount above is cleared"
            if asm._use_api()
            else "to generate on the subscription"
        )
        print(
            f"\nPre-flight only - nothing generated. Re-run with --confirm {tail}.",
            file=sys.stderr,
        )
        return 0
    if not resolved:
        print("nothing resolved to generate", file=sys.stderr)
        return 2
    return generate(args, kind, resolved)


if __name__ == "__main__":
    sys.exit(main())
